(function(g){var window=this;'use strict';var qKa=function(a,b){return g.Lb(a,b)},rKa=function(a){if(a instanceof g.Wi)return a;
if("function"==typeof a.ph)return a.ph(!1);if(g.La(a)){var b=0,c=new g.Wi;c.next=function(){for(;;){if(b>=a.length)throw g.Fn;if(b in a)return a[b++];b++}};
return c}throw Error("Not implemented");},sKa=function(a,b,c){if(g.La(a))try{g.zb(a,b,c)}catch(d){if(d!==g.Fn)throw d;
}else{a=rKa(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(d){if(d!==g.Fn)throw d;}}},M4=function(a,b,c){a.l.set(b,c)},N4=function(a){M4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ra()).toString(36));
return a},O4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Ym(a.l,b,c)},tKa=function(a,b){var c=[];
sKa(b,function(d){try{var e=g.Vn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Un(e)&&c.push(d)},a);
return c},uKa=function(a,b){b=tKa(a,b);
g.zb(b,function(c){g.Vn.prototype.remove.call(this,c)},a)},vKa=function(a){if(a.V){if(a.V.locationOverrideToken)return{locationOverrideToken:a.V.locationOverrideToken};
if(null!=a.V.latitudeE7&&null!=a.V.longitudeE7)return{latitudeE7:a.V.latitudeE7,longitudeE7:a.V.longitudeE7}}return null},wKa=function(a,b){g.fb(a,b)||a.push(b)},P4=function(a){var b=0,c;
for(c in a)b++;return b},xKa=function(a,b){b=b instanceof g.Ac?b:g.Ic(b,/^data:image\//i.test(b));
a.src=g.Bc(b)},yKa=function(a){try{return g.B.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},zKa=function(a){if(a.zg&&"function"==typeof a.zg)return a.zg();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ib(a)},AKa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)g.zb(a,b,void 0);else{if(a.Bh&&"function"==typeof a.Bh)var c=a.Bh();else if(a.zg&&"function"==typeof a.zg)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Jb(a);d=zKa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},BKa=function(a,b,c,d){var e=new g.Mm(null,void 0);
a&&g.Nm(e,a);b&&g.Om(e,b);c&&g.Pm(e,c);d&&(e.J=d);return e},Q4=function(){},R4=function(a,b){g.Pq[a]=!0;
var c=g.Nq();c&&c.publish.apply(c,arguments);g.Pq[a]=!1},S4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Jm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",CKa(this,a.capabilities||""),DKa(this,a.experiments||""))},CKa=function(a,b){a.capabilities.clear();
g.Je(b.split(","),g.Pa(qKa,EKa)).forEach(function(c){a.capabilities.add(c)})},DKa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},T4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},U4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},FKa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},GKa=function(a){return new T4(a)},HKa=function(a){return Array.isArray(a)?g.Mc(a,GKa):[]},V4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},W4=function(a){return Array.isArray(a)?"["+g.Mc(a,V4).join(",")+"]":"null"},X4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},IKa=function(a){return g.Mc(a,function(b){return{key:b.id,
name:b.name}})},Y4=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},Z4=function(a,b){return g.cb(a,function(c){return U4(c,b)})},JKa=function(){var a=(0,g.hv)();
a&&uKa(a,a.i.ph(!0))},$4=function(){var a=g.kv("yt-remote-connected-devices")||[];
g.wb(a);return a},KKa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Mc(a,function(d,e){return 0==e?d:d.substring(c.length)})},LKa=function(a){g.jv("yt-remote-connected-devices",a,86400)},b5=function(){if(a5)return a5;
var a=g.kv("yt-remote-device-id");a||(a=X4(),g.jv("yt-remote-device-id",a,31536E3));for(var b=$4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return a5=d},c5=function(){var a=$4(),b=b5();
g.fb(a,b);g.nv()&&g.yb(a,b);a=KKa(a);if(g.gb(a))try{g.Eo("remote_sid")}catch(c){}else try{g.Co("remote_sid",a.join(","),-1)}catch(c){}},MKa=function(){return g.kv("yt-remote-session-browser-channel")},NKa=function(){return g.kv("yt-remote-local-screens")||[]},OKa=function(){g.jv("yt-remote-lounge-token-expiration",!0,86400)},PKa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Mc(NKa(),function(d){return d.loungeToken}),c=g.Mc(a,function(d){return d.loungeToken});
g.fh(c,function(d){return!g.fb(b,d)})&&OKa();
g.jv("yt-remote-local-screens",a,31536E3)},QKa=function(a,b){g.jv("yt-remote-session-browser-channel",a);
g.jv("yt-remote-session-screen-id",b);a=$4();b=b5();g.fb(a,b)||a.push(b);LKa(a);c5()},d5=function(a){a||(g.mv("yt-remote-session-screen-id"),g.mv("yt-remote-session-video-id"));
c5();a=$4();g.kb(a,b5());LKa(a)},RKa=function(){if(!e5){var a=g.fo();
a&&(e5=new g.Pn(a))}},SKa=function(){RKa();
return e5?!!e5.get("yt-remote-use-staging-server"):!1},f5=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},TKa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},UKa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},g5=function(a){a.length?VKa(a.shift(),function(){g5(a)}):h5()},WKa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},VKa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Td(d,g.gg(a));(document.head||document.documentElement).appendChild(d)},XKa=function(){var a=f5(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},h5=function(){var a=UKa();
a&&a(!1,"No cast extension found")},i5=function(){if(YKa){var a=2,b=UKa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;VKa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",h5,c)}},ZKa=function(){i5();
var a=XKa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");g5(a)},aLa=function(){i5();
var a=XKa();a.push.apply(a,g.ma($Ka.map(WKa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");g5(a)},j5=function(a,b,c){g.F.call(this);
this.G=null!=c?(0,g.C)(a,c):a;this.Cf=b;this.C=(0,g.C)(this.PL,this);this.i=!1;this.l=0;this.u=this.Fb=null;this.B=[]},k5=function(a,b,c){g.F.call(this);
this.B=null!=c?a.bind(c):a;this.Cf=b;this.u=null;this.i=!1;this.l=0;this.Fb=null},l5=function(a){a.Fb=g.Hm(function(){a.Fb=null;
a.i&&!a.l&&(a.i=!1,l5(a))},a.Cf);
var b=a.u;a.u=null;a.B.apply(null,b)},m5=function(a){if(g.B.JSON)try{return g.B.JSON.parse(a)}catch(b){}return yKa(a)},n5=function(){},o5=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.B.setTimeout(function(){a()},b)},q5=function(a){p5.dispatchEvent(new bLa(p5,a))},bLa=function(a,b){g.xl.call(this,"statevent",a);
this.stat=b},r5=function(){},cLa=function(){},eLa=function(a){return(a=dLa(a))?new ActiveXObject(a):new XMLHttpRequest},dLa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},s5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.d0(this);this.u=new g.Gm;this.u.setInterval(250)},gLa=function(a,b,c){a.Hq=1;
a.zl=N4(b.clone());a.Io=c;a.G=!0;fLa(a,null)},t5=function(a,b,c,d,e){a.Hq=1;
a.zl=N4(b.clone());a.Io=null;a.G=c;e&&(a.TI=!1);fLa(a,d)},fLa=function(a,b){a.xq=Date.now();
u5(a);a.Am=a.zl.clone();O4(a.Am,"t",a.J);a.du=0;a.He=a.i.Hz(a.i.Kt()?b:null);0<a.By&&(a.Sw=new k5((0,g.C)(a.PJ,a,a.He),a.By));a.B.Pa(a.He,"readystatechange",a.fS);b=a.Sm?g.Sb(a.Sm):{};a.Io?(a.Gx="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.He.send(a.Am,a.Gx,a.Io,b)):(a.Gx="GET",a.TI&&!g.ze&&(b.Connection="close"),a.He.send(a.Am,a.Gx,null,b));a.i.zi(1)},jLa=function(a,b,c){for(var d=!0;!a.yn&&a.du<c.length;){var e=hLa(a,c);
if(e==v5){4==b&&(a.ul=4,q5(15),d=!1);break}else if(e==iLa){a.ul=4;q5(16);d=!1;break}else w5(a,e)}4==b&&0==c.length&&(a.ul=1,q5(17),d=!1);a.Li=a.Li&&d;d||(x5(a),y5(a))},hLa=function(a,b){var c=a.du,d=b.indexOf("\n",c);
if(-1==d)return v5;c=Number(b.substring(c,d));if(isNaN(c))return iLa;d+=1;if(d+c>b.length)return v5;b=b.substr(d,c);a.du=d+c;return b},lLa=function(a,b){a.xq=Date.now();
u5(a);var c=b?window.location.hostname:"";a.Am=a.zl.clone();M4(a.Am,"DOMAIN",c);M4(a.Am,"t",a.J);try{a.Qi=new ActiveXObject("htmlfile")}catch(m){x5(a);a.ul=7;q5(22);y5(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in z5)f=z5[f];else if(f in kLa)f=z5[f]=kLa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
z5[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ed(g.cc("b/12014412"),d+"</body></html>");a.Qi.open();a.Qi.write(g.ad(c));a.Qi.close();a.Qi.parentWindow.m=(0,g.C)(a.ER,a);a.Qi.parentWindow.d=(0,g.C)(a.iI,a,!0);a.Qi.parentWindow.rpcClose=(0,g.C)(a.iI,a,!1);c=a.Qi.createElement("DIV");a.Qi.parentWindow.document.body.appendChild(c);d=g.Fc(a.Am.toString());d=g.md(g.Bc(d));d=g.ed(g.cc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.fd(c,d);a.i.zi(1)},u5=function(a){a.QC=Date.now()+
a.C;
mLa(a,a.C)},mLa=function(a,b){if(null!=a.Mq)throw Error("WatchDog timer not null");
a.Mq=o5((0,g.C)(a.MR,a),b)},A5=function(a){a.Mq&&(g.B.clearTimeout(a.Mq),a.Mq=null)},y5=function(a){a.i.RD()||a.yn||a.i.Au(a)},x5=function(a){A5(a);
g.xi(a.Sw);a.Sw=null;a.u.stop();g.ZEa(a.B);if(a.He){var b=a.He;a.He=null;b.abort();b.dispose()}a.Qi&&(a.Qi=null)},w5=function(a,b){try{a.i.bI(a,b),a.i.zi(4)}catch(c){}},oLa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;nLa(a,b,function(h){h?c(!0):g.B.setTimeout(function(){oLa(a,b,c,d,f)},f)})}},nLa=function(a,b,c){var d=new Image;
d.onload=function(){try{B5(d),c(!0)}catch(e){}};
d.onerror=function(){try{B5(d),c(!1)}catch(e){}};
d.onabort=function(){try{B5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{B5(d),c(!1)}catch(e){}};
g.B.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
xKa(d,a)},B5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},C5=function(a){g.Wl.call(this);
this.headers=new g.Jm;this.ra=a||null;this.B=!1;this.ma=this.i=null;this.Fa=this.V="";this.G=0;this.u="";this.C=this.Aa=this.L=this.xa=!1;this.J=0;this.X=null;this.La="";this.Y=this.Da=!1},pLa=function(a){return g.xe&&g.ae(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},qLa=function(a){return"content-type"==a.toLowerCase()},sLa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.G=5;rLa(a);D5(a)},rLa=function(a){a.xa||(a.xa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},uLa=function(a){if(a.B&&"undefined"!=typeof g.h0)if(a.ma[1]&&4==E5(a)&&2==a.getStatus())F5(a,"Local request error detected and ignored");
else if(a.L&&4==E5(a))g.Hm(a.YH,0,a);else if(a.dispatchEvent("readystatechange"),a.Nd()){F5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vd(1,String(a.V));if(!f&&g.B.self&&g.B.self.location){var h=g.B.self.location.protocol;f=h.substr(0,h.length-1)}e=!tLa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<E5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";rLa(a)}}finally{D5(a)}}},D5=function(a,b){if(a.i){vLa(a);
var c=a.i,d=a.ma[0]?g.Ia:null;a.i=null;a.ma=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},vLa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.B.clearTimeout(a.X),a.X=null)},E5=function(a){return a.i?a.i.readyState:0},G5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},F5=function(a,b){return b+" ["+a.Fa+" "+a.V+" "+a.getStatus()+"]"},wLa=function(a){this.i=a;
this.l=new n5},xLa=function(a){var b=H5(a.i,a.Dr,"/mail/images/cleardot.gif");
N4(b);oLa(b.toString(),5E3,(0,g.C)(a.JM,a),3,2E3);a.zi(1)},J5=function(a){var b=a.i.L;
if(null!=b)q5(5),b?(q5(11),I5(a.i,a,!1)):(q5(12),I5(a.i,a,!0));else if(a.Jg=new s5(a,void 0,void 0,void 0),a.Jg.Sm=a.Cy,b=a.i,b=H5(b,b.Kt()?a.lr:null,a.Dy),q5(5),!g.xe||g.be(10))O4(b,"TYPE","xmlhttp"),t5(a.Jg,b,!1,a.lr,!1);else{O4(b,"TYPE","html");var c=a.Jg;a=!!a.lr;c.Hq=3;c.zl=N4(b.clone());lLa(c,a)}},K5=function(a,b,c){this.eb=1;
this.i=[];this.u=[];this.B=new n5;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},yLa=function(a,b){this.i=a;
this.map=b;this.context=null},zLa=function(a,b,c,d){g.xl.call(this,"timingevent",a);
this.size=b;this.Et=d},ALa=function(a){g.xl.call(this,"serverreachability",a)},DLa=function(a){BLa(a);
if(3==a.eb){var b=a.Ts++,c=a.bv.clone();M4(c,"SID",a.l);M4(c,"RID",b);M4(c,"TYPE","terminate");L5(a,c);b=new s5(a,a.l,b,void 0);b.Hq=2;b.zl=N4(c.clone());xKa(new Image,b.zl.toString());b.xq=Date.now();u5(b)}CLa(a)},ELa=function(a){a.hN(1,0);
a.bv=H5(a,null,a.Ey);M5(a)},BLa=function(a){a.El&&(a.El.abort(),a.El=null);
a.Yd&&(a.Yd.cancel(),a.Yd=null);a.wk&&(g.B.clearTimeout(a.wk),a.wk=null);N5(a);a.xg&&(a.xg.cancel(),a.xg=null);a.Ll&&(g.B.clearTimeout(a.Ll),a.Ll=null)},FLa=function(a,b){if(0==a.eb)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new yLa(a.KO++,b));2!=a.eb&&3!=a.eb||M5(a)},GLa=function(a){var b=0;
a.Yd&&b++;a.xg&&b++;return b},M5=function(a){a.xg||a.Ll||(a.Ll=o5((0,g.C)(a.gI,a),0),a.Qp=0)},ILa=function(a,b){if(1==a.eb){if(!b){a.Ts=Math.floor(1E5*Math.random());
b=a.Ts++;var c=new s5(a,"",b,void 0);c.Sm=a.mj;var d=O5(a),e=a.bv.clone();M4(e,"RID",b);M4(e,"CVER","1");L5(a,e);gLa(c,e,d);a.xg=c;a.eb=2}}else 3==a.eb&&(b?HLa(a,b):0==a.i.length||a.xg||HLa(a))},HLa=function(a,b){if(b)if(6<a.zn){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Ts-1;b=O5(a)}else c=b.L,b=b.Io;else c=a.Ts++,b=O5(a);var d=a.bv.clone();M4(d,"SID",a.l);M4(d,"RID",c);M4(d,"AID",a.hq);L5(a,d);c=new s5(a,a.l,c,a.Qp+1);c.Sm=a.mj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.xg=c;gLa(c,d,b)},L5=function(a,b){a.xf&&(a=a.xf.NF())&&g.Bb(a,function(c,d){M4(b,d,c)})},O5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.zn&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={jp:e.jp},f++){e.jp=a.i[f].i;var h=a.i[f].map;e.jp=6>=a.zn?f:e.jp-d;try{g.Bb(h,function(l){return function(m,n){c.push("req"+l.jp+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.jp+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},JLa=function(a){a.Yd||a.wk||(a.G=1,a.wk=o5((0,g.C)(a.fI,a),0),a.Ep=0)},P5=function(a){if(a.Yd||a.wk||3<=a.Ep)return!1;
a.G++;a.wk=o5((0,g.C)(a.fI,a),KLa(a,a.Ep));a.Ep++;return!0},I5=function(a,b,c){a.Ex=c;
a.nj=b.ek;a.C||ELa(a)},N5=function(a){null!=a.Gn&&(g.B.clearTimeout(a.Gn),a.Gn=null)},KLa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Q5=function(a,b){if(2==b||9==b){var c=null;
a.xf&&(c=null);var d=(0,g.C)(a.KS,a);c||(c=new g.Mm("//www.google.com/images/cleardot.gif"),N4(c));nLa(c.toString(),1E4,d)}else q5(2);LLa(a,b)},LLa=function(a,b){a.eb=0;
a.xf&&a.xf.fF(b);CLa(a);BLa(a)},CLa=function(a){a.eb=0;
a.nj=-1;if(a.xf)if(0==a.u.length&&0==a.i.length)a.xf.rz();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.xf.rz(b)}},H5=function(a,b,c){var d=g.Um(c);
if(""!=d.i)b&&g.Om(d,b+"."+d.i),g.Pm(d,d.u);else{var e=window.location;d=BKa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Tr&&g.Bb(a.Tr,function(f,h){M4(d,h,f)});
M4(d,"VER",a.zn);L5(a,d);return d},MLa=function(){},NLa=function(){this.i=[];
this.l=[]},OLa=function(a,b){this.action=a;
this.params=b||{}},R5=function(a,b){g.F.call(this);
this.i=new g.J(this.wR,0,this);g.G(this,this.i);this.Cf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},S5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ma=a;this.G=b;this.u=new g.On;this.l=new R5(this.qS,this);this.i=null;this.X=!1;this.C=null;this.V="";this.L=this.B=0;this.J=[];this.ra=c;this.Y=d;this.xa=e},PLa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Ex,sessionId:a.i.l,arrayId:a.i.hq}},QLa=function(a,b){a.L=b||0;
a.l.stop();T5(a);a.i&&(3==a.i.getState()&&ILa(a.i),DLa(a.i));a.L=0},U5=function(a){return!!a.i&&3==a.i.getState()},T5=function(a){if(a.i){var b=a.Y(),c=a.i.mj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.mj=c}},V5=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.vd(4,a))||"";b&&(this.port=":"+b);this.domain=g.wd(a)||"";a=g.Uc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yc(a,"10.0")&&(this.l=!1))},W5=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.Hd(c+b,{})},X5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.B,d,!0),onError:g.Pa(a.u,e),onTimeout:g.Pa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.tp(b,a)},ULa=function(){var a=RLa;
SLa();Y5.push(a);TLa()},Z5=function(a,b){SLa();
var c=VLa(a,String(b));g.gb(Y5)?WLa(c):(TLa(),g.zb(Y5,function(d){d(c)}))},SLa=function(){Y5||(Y5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",Y5,void 0))},WLa=function(a){var b=($5+1)%50;
$5=b;a6[b]=a;b6||(b6=49==b)},TLa=function(){var a=Y5;
if(a6[0]){var b=b6?$5:-1;do{b=(b+1)%50;var c=a6[b];g.zb(a,function(d){d(c)})}while(b!=$5);
a6=Array(50);$5=-1;b6=!1}},VLa=function(a,b){var c=(Date.now()-XLa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},c6=function(a){g.P.call(this);
this.G=a;this.screens=[]},YLa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},ZLa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Je(a.screens,function(f){return!!Y4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=YLa(a,b[d])||c;return c},$La=function(a,b){var c=a.screens.length;
a.screens=g.Je(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},d6=function(a,b,c,d,e){g.P.call(this);
this.u=a;this.J=b;this.B=c;this.G=d;this.C=e;this.l=0;this.i=null;this.Fb=NaN},f6=function(a){c6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;e6(this);this.info("Initializing with "+W4(this.screens))},aMa=function(a){if(a.screens.length){var b=g.Mc(a.screens,function(d){return d.id}),c=W5(a.l,"/pairing/get_lounge_token_batch");
X5(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.FN,a),(0,g.C)(a.EN,a))}},e6=function(a){if(g.No("deprecate_pair_servlet_enabled"))return ZLa(a,[]);
var b=HKa(NKa());b=g.Je(b,function(c){return!c.uuid});
return ZLa(a,b)},g6=function(a,b){PKa(g.Mc(a.screens,FKa));
b&&OKa()},i6=function(a,b){g.P.call(this);
this.G=b;b=(b=g.kv("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.G(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.fb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;h6("Initialized with "+g.xj(this.i))},j6=function(a,b,c){var d=W5(a.C,"/pairing/get_screen_availability");
X5(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},k6=function(a,b){a:if(P4(b)!=P4(a.i))var c=!1;
else{c=g.Jb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(h6("Updated online screens: "+g.xj(a.i)),a.i=b,a.W("screenChange"));bMa(a)},l6=function(a){isNaN(a.u)||g.op(a.u);
a.u=g.mp((0,g.C)(a.RB,a),0<a.B&&a.B<g.Ra()?2E4:1E4)},h6=function(a){Z5("OnlineScreenService",a)},cMa=function(a){var b={};
g.zb(a.G(),function(c){c.token?b[c.token]=c.id:this.Kd("Requesting availability of screen w/o lounge token.")});
return b},bMa=function(a){a=g.Jb(g.Cb(a.i,function(b){return b}));
g.wb(a);a.length?g.jv("yt-remote-online-screen-ids",a.join(","),60):g.mv("yt-remote-online-screen-ids")},m6=function(a,b){b=void 0===b?!1:b;
c6.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};dMa(this)},fMa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Wg(),l=c?Z4(h,c):null;c&&(a.J||l)||(l=Z4(h,b));if(l){l.uuid=b;var m=n6(a,l);j6(a.i,m,function(n){e(n?m:null)})}else c?eMa(a,c,(0,g.C)(function(n){var p=n6(this,new T4({name:d,
screenId:c,loungeToken:n,dialId:b||""}));j6(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},gMa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},hMa=function(a,b,c){j6(a.i,b,c)},eMa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.tp(W5(a.B,"/pairing/get_lounge_token_batch"),e)},iMa=function(a){a.screens=a.l.Wg();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+W4(a.screens))},dMa=function(a){o6(a);
a.l=new f6(a.B);a.l.subscribe("screenChange",(0,g.C)(a.LN,a));iMa(a);a.J||(a.u=HKa(g.kv("yt-remote-automatic-screen-cache")||[]));o6(a);a.info("Initializing automatic screens: "+W4(a.u));a.i=new i6(a.B,(0,g.C)(a.Wg,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.W("onlineScreenChange")},a))},n6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Z4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||jMa(a));o6(a);a.C[b.uuid]=b.id;g.jv("yt-remote-device-id-map",a.C,31536E3);return b},jMa=function(a){a=g.Je(a.u,function(b){return"shortLived"!=b.idType});
g.jv("yt-remote-automatic-screen-cache",g.Mc(a,FKa))},o6=function(a){a.C=g.kv("yt-remote-device-id-map")||{}},p6=function(a,b,c){g.P.call(this);
this.xa=c;this.u=a;this.i=b;this.B=null},q6=function(a,b){a.B=b;
a.W("sessionScreen",a.B)},kMa=function(a,b){a.B&&(a.B.token=b,n6(a.u,a.B));
a.W("sessionScreen",a.B)},r6=function(a,b){Z5(a.xa,b)},s6=function(a,b,c){p6.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.l=null;this.Y=(0,g.C)(this.UL,this);this.ra=(0,g.C)(this.PR,this);this.X=g.mp(function(){lMa(d,null)},12E4);
this.J=this.C=this.G=this.L=0;this.ma=!1;this.V="unknown"},t6=function(a,b){g.op(a.J);
a.J=0;0==b?mMa(a):a.J=g.mp(function(){mMa(a)},b)},mMa=function(a){nMa(a,"getLoungeToken");
g.op(a.C);a.C=g.mp(function(){oMa(a,null)},3E4)},nMa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.xj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.C)(function(){r6(this,"Failed to send message: "+b+".")},a)):r6(a,"Sending yt message without session: "+g.xj(c))},u6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.bG(b,function(c){q6(a,c)},function(){return a.Yf()},5)):a.Yf(Error("Waiting for session status timed out."))},qMa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new T4(b);pMa(a,d,function(e){e?(a.ma=!0,n6(a.u,d),q6(a,d),a.V="unknown",t6(a,c)):(g.So(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Yf())},5)},lMa=function(a,b){g.op(a.X);
a.X=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?qMa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.So(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),u6(a,b.screenId))):(g.So(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),u6(a,b.screenId)):u6(a,b.screenId):a.Yf(Error("Waiting for session status timed out."))},oMa=function(a,b){g.op(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,t6(a,3E4)):(kMa(a,b.loungeToken),a.ma=!1,a.V="unknown",t6(a,b.loungeTokenRefreshIntervalMs))},pMa=function(a,b,c,d){g.op(a.G);
a.G=0;hMa(a.u,b,function(e){e||0>d?c(e):a.G=g.mp(function(){pMa(a,b,c,d-1)},300)})},rMa=function(a){g.op(a.L);
a.L=0;g.op(a.G);a.G=0;g.op(a.X);a.X=0;g.op(a.C);a.C=0;g.op(a.J);a.J=0},v6=function(a,b,c,d){p6.call(this,a,b,"DialSession");
this.config_=d;this.l=this.L=null;this.ra="";this.Da=c;this.Ea=null;this.X=g.Ia;this.V=NaN;this.Aa=(0,g.C)(this.VL,this);this.C=g.Ia;this.J=this.G=0;this.Y=!1;this.ma="unknown"},w6=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},sMa=function(a){a.C=a.u.TD(a.ra,a.i.label,a.i.friendlyName,w6(a),function(b,c){a.C=g.Ia;
a.Y=!0;q6(a,b);"shortLived"==b.idType&&0<c&&x6(a,c)},function(b){a.C=g.Ia;
a.Yf(b)})},tMa=function(a){var b={};
b.pairingCode=a.ra;b.theme=a.Da;SKa()&&(b.env_useStageMdx=1);return g.Fd(b)},y6=function(a){return new Promise(function(b){a.ra=X4();
if(a.Ea){var c=new chrome.cast.DialLaunchResponse(!0,tMa(a));b(c);sMa(a)}else a.X=function(){g.op(a.V);a.X=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,tMa(a));b(d);sMa(a)},a.V=g.mp(function(){a.X()},100)})},vMa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new T4(b);return(new Promise(function(e){uMa(a,d,function(f){f?(a.Y=!0,n6(a.u,d),q6(a,d),x6(a,c)):g.So(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):y6(a)})},wMa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){fMa(a.u,c,b,d,function(f){f&&f.token&&q6(a,f);e(f)},function(f){r6(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):y6(a)})},uMa=function(a,b,c,d){g.op(a.G);
a.G=0;hMa(a.u,b,function(e){e||0>d?c(e):a.G=g.mp(function(){uMa(a,b,c,d-1)},300)})},x6=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
w6(a)&&(g.op(a.J),a.J=0,0==b?xMa(a):a.J=g.mp(function(){xMa(a)},b))},xMa=function(a){w6(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ma=c,x6(a,3E4)):(a.Y=!1,a.ma="unknown",kMa(a,b.loungeToken),x6(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ma="noLoungeTokenResponse";x6(a,3E4)})},yMa=function(a){g.op(a.G);
a.G=0;g.op(a.J);a.J=0;a.C();a.C=function(){};
g.op(a.V)},z6=function(a,b){p6.call(this,a,b,"ManualSession");
this.l=g.mp((0,g.C)(this.iq,this,null),150)},A6=function(a,b){g.P.call(this);
this.config_=b;this.l=a;this.J=b.appId||"233637DE";this.B=b.theme||"cl";this.L=b.disableCastApi||!1;this.V=b.forceMirroring||!1;this.i=null;this.G=!1;this.u=[];this.C=(0,g.C)(this.MQ,this)},zMa=function(a,b){return b?g.cb(a.u,function(c){return U4(b,c.label)},a):null},B6=function(a){Z5("Controller",a)},RLa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},C6=function(a){return a.G||!!a.u.length||!!a.i},D6=function(a,b,c){b!=a.i&&(g.xi(a.i),(a.i=b)?(c?a.W("yt-remote-cast2-receiver-resumed",
b.i):a.W("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.eI,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.iq(null)):a.W("yt-remote-cast2-session-change",null))},AMa=function(a){var b=a.l.SD(),c=a.i&&a.i.i;
a=g.Mc(b,function(d){c&&U4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=zMa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},FMa=function(a,b,c,d){d.disableCastApi?E6("Cannot initialize because disabled by Mdx config."):BMa()?CMa(b,d)&&(F6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?DMa(a,c):(window.__onGCastApiAvailable=function(e,f){e?DMa(a,c):(G6("Failed to load cast API: "+f),H6(!1),F6(!1),g.mv("yt-remote-cast-available"),g.mv("yt-remote-cast-receiver"),
EMa(),c(!1))},d.loadCastApiSetupScript?g.ov("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=f5()&&ZKa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?h5():89<=f5()?aLa():(i5(),g5($Ka.map(WKa))))):E6("Cannot initialize because not running Chrome")},EMa=function(){E6("dispose");
var a=I6();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);GMa(!1);g.Sq(J6);J6.length=0},K6=function(){return!!g.kv("yt-remote-cast-installed")},HMa=function(){var a=g.kv("yt-remote-cast-receiver");
return a?a.friendlyName:null},IMa=function(){E6("clearCurrentReceiver");
g.mv("yt-remote-cast-receiver")},JMa=function(){return K6()?I6()?I6().getCastSession():(G6("getCastSelector: Cast is not initialized."),null):(G6("getCastSelector: Cast API is not installed!"),null)},M6=function(){K6()?I6()?L6()?(E6("Requesting cast selector."),I6().requestSession()):(E6("Wait for cast API to be ready to request the session."),J6.push(g.Rq("yt-remote-cast2-api-ready",M6))):G6("requestCastSelector: Cast is not initialized."):G6("requestCastSelector: Cast API is not installed!")},N6=
function(a,b){L6()?I6().setConnectedScreenStatus(a,b):G6("setConnectedScreenStatus called before ready.")},BMa=function(){var a=0<=g.Uc.search(/ (CrMo|Chrome|CriOS)\//);
return g.lB||a},KMa=function(a,b){I6().init(a,b)},CMa=function(a,b){var c=!1;
I6()||(a=new A6(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.jv("yt-remote-cast-available",d);R4("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){E6("onReceiverSelected: "+d.friendlyName);
g.jv("yt-remote-cast-receiver",d);R4("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){E6("onReceiverResumed: "+d.friendlyName);
g.jv("yt-remote-cast-receiver",d);R4("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){E6("onSessionChange: "+V4(d));
d||g.mv("yt-remote-cast-receiver");R4("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
E6("cloudview.createSingleton_: "+c);return c},I6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},DMa=function(a,b){H6(!0);
F6(!1);KMa(a,function(c){c?(GMa(!0),g.Tq("yt-remote-cast2-api-ready")):(G6("Failed to initialize cast API."),H6(!1),g.mv("yt-remote-cast-available"),g.mv("yt-remote-cast-receiver"),EMa());b(c)})},E6=function(a){Z5("cloudview",a)},G6=function(a){Z5("cloudview",a)},H6=function(a){E6("setCastInstalled_ "+a);
g.jv("yt-remote-cast-installed",a)},L6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},GMa=function(a){E6("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},F6=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},O6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.J=0;this.trackData=null;this.hasNext=this.Cj=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},P6=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Cj=!1;a.hasNext=!1;a.J=0;a.G=g.Ra();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},Q6=function(a){return a.tc()?(g.Ra()-a.G)/1E3:0},R6=function(a,b){a.J=b;
a.G=g.Ra()},S6=function(a){switch(a.playerState){case 1:case 1081:return(g.Ra()-a.G)/1E3+a.J;
case -1E3:return 0}return a.J},T6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&P6(a)},U6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Tb(a.trackData);b.hasPrevious=a.Cj;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.G;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},W6=function(a,b){g.P.call(this);
this.eb=0;this.u=a;this.C=[];this.B=new NLa;this.l=this.i=null;this.L=(0,g.C)(this.rP,this);this.G=(0,g.C)(this.Ws,this);this.J=(0,g.C)(this.qP,this);this.V=(0,g.C)(this.yP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.dC,this),LMa(this))):c=3;0!=c&&(b?this.dC(c):g.mp((0,g.C)(function(){this.dC(c)},this),0));
(a=JMa())&&V6(this,a);this.subscribe("yt-remote-cast2-session-change",this.V)},X6=function(a){return new O6(a.u.getPlayerContextData())},LMa=function(a){g.zb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Pa(this.JQ,b),this))},a)},MMa=function(a){g.zb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},Y6=function(a){return 1==a.getState()},Z6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},a7=function(a,b,c){var d=X6(a);
R6(d,c);-1E3!=d.playerState&&(d.playerState=b);$6(a,d)},b7=function(a,b,c){a.u.sendMessage(b,c)},$6=function(a,b){MMa(a);
a.u.setPlayerContextData(U6(b));LMa(a)},V6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.G),a.Ws(null));
a.l=b;a.l&&(Z5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.G),a.l.media.length&&a.Ws(a.l.media[0]))},NMa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=X6(a);b.contentId!=d.videoId&&Z5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;R6(d,a.i.getEstimatedTime());$6(a,d)}else Z5("CP","No cast media video. Ignoring state update.")},c7=function(a,b,c){return(0,g.C)(function(d){this.Kd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Kd("Retrying "+b+" using MDx browser channel."),b7(this,b,c))},a)},d7=function(a,b,c){g.P.call(this);
this.C=NaN;this.ma=!1;this.L=this.J=this.X=this.Y=NaN;this.V=[];this.B=this.G=this.u=this.dc=this.i=null;this.xa=a;this.V.push(g.Sp(window,"beforeunload",(0,g.C)(this.BN,this)));this.l=[];this.dc=new O6;this.Aa=b.id;this.ra=b.idType;this.i=OMa(this,c);this.i.subscribe("handlerOpened",this.vP,this);this.i.subscribe("handlerClosed",this.sP,this);this.i.subscribe("handlerError",this.tP,this);this.i.subscribe("handlerMessage",this.uP,this);this.i.fx(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.dc.videoId;g.nv()&&g.jv("yt-remote-session-video-id",d)},this)},e7=function(a){Z5("conn",a)},OMa=function(a,b){return new S5(W5(a.xa,"/bc"),b,!1,function(){return a.XD()},"shortLived"==a.ra)},f7=function(a,b){a.W("proxyStateChange",b)},PMa=function(a){a.C=g.mp((0,g.C)(function(){e7("Connecting timeout");
this.Mp(1)},a),2E4)},g7=function(a){g.op(a.C);
a.C=NaN},h7=function(a){g.op(a.Y);
a.Y=NaN},QMa=function(a){i7(a);
a.X=g.mp((0,g.C)(function(){j7(this,"getNowPlaying")},a),2E4)},i7=function(a){g.op(a.X);
a.X=NaN},SMa=function(a,b){b&&(g7(a),h7(a));
var c=U5(a.i)&&isNaN(a.C);b==c?b&&(f7(a,1),j7(a,"getSubtitlesTrack")):b?(a.ZF()&&a.dc.reset(),f7(a,1),j7(a,"getNowPlaying"),RMa(a)):a.Mp(1)},TMa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.dc.videoId&&(g.Ob(b.params)?a.dc.trackData=null:a.dc.trackData=b.params,a.W("remotePlayerChange"))},UMa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.dc.listId=b.params.listId||a.dc.listId;T6(a.dc,c,d);a.W("remoteQueueChange")},WMa=function(a,b){b.params=b.params||{};
UMa(a,b);VMa(a,b);a.W("autoplayDismissed")},VMa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
R6(a.dc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.dc.playerState&&(c=-1E3);a.dc.playerState=c;c=Number(b.params.loadedTime);a.dc.L=isNaN(c)?0:c;c=Number(b.params.duration);a.dc.C=isNaN(c)?0:c;c=a.dc;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.dc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.dc.playerState?QMa(a):i7(a);a.W("remotePlayerChange")},XMa=function(a,b){if(-1E3!=a.dc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.dc.playerState=c;b=parseInt(b.params.currentTime,10);R6(a.dc,isNaN(b)?0:b);a.W("remotePlayerChange")}},YMa=function(a,b){var c="true"==b.params.muted;
a.dc.volume=parseInt(b.params.volume,10);a.dc.muted=c;a.W("remotePlayerChange")},ZMa=function(a,b){a.G=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},$Ma=function(a,b){var c="true"==b.params.hasNext;
a.dc.Cj="true"==b.params.hasPrevious;a.dc.hasNext=c;a.W("previousNextChange")},RMa=function(a){g.op(a.L);
a.L=g.mp((0,g.C)(a.Mp,a,1),864E5)},j7=function(a,b,c){c?e7("Sending: action="+b+", params="+g.xj(c)):e7("Sending: action="+b);
a.i.sendMessage(b,c)},k7=function(a){c6.call(this,"ScreenServiceProxy");
this.Bf=a;this.i=[];this.i.push(this.Bf.$_s("screenChange",(0,g.C)(this.ZL,this)));this.i.push(this.Bf.$_s("onlineScreenChange",(0,g.C)(this.qQ,this)))},dNa=function(a,b){RKa();
if(!e5||!e5.get("yt-remote-disable-remote-module-for-dev")){b=g.N("MDX_CONFIG")||b;JKa();c5();l7||(l7=new V5(b?b.loungeApiHost:void 0),SKa()&&(l7.i="/api/loungedev"));m7||(m7=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",m7,void 0));aNa();var c=n7();if(!c){var d=new m6(l7,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=n7();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});FMa(a,d,function(f){f?o7()&&N6(o7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){R4("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),p7("Initializing: "+g.xj(b)),q7.push(g.Rq("yt-remote-cast2-availability-change",function(){R4("yt-remote-receiver-availability-change")})),
q7.push(g.Rq("yt-remote-cast2-receiver-selected",function(){r7(null);
R4("yt-remote-auto-connect","cast-selector-receiver")})),q7.push(g.Rq("yt-remote-cast2-receiver-resumed",function(){R4("yt-remote-receiver-resumed","cast-selector-receiver")})),q7.push(g.Rq("yt-remote-cast2-session-change",bNa)),q7.push(g.Rq("yt-remote-connection-change",function(f){f?N6(o7(),"YouTube TV"):s7()||(N6(null,null),IMa())})),a=t7(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.No("desktop_enable_autoplay")&&e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=
b.theme)&&(a.theme=b),p7(" -- with channel params: "+g.xj(a)),a?(g.jv("yt-remote-session-app",a.app),g.jv("yt-remote-session-name",a.name)):(g.mv("yt-remote-session-app"),g.mv("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),o7()||cNa())}},eNa=function(){var a=n7().Bf.$_gos();
var b=u7();b&&v7()&&(Y4(a,b)||a.push(b));return IKa(a)},w7=function(){var a=fNa();
!a&&K6()&&HMa()&&(a={key:"cast-selector-receiver",name:HMa()});return a},fNa=function(){var a=eNa(),b=u7();
b||(b=s7());return g.cb(a,function(c){return b&&U4(b,c.key)?!0:!1})},u7=function(){var a=o7();
if(!a)return null;var b=n7().Wg();return Z4(b,a)},bNa=function(a){p7("remote.onCastSessionChange_: "+V4(a));
if(a){var b=u7();if(b&&b.id==a.id){if(N6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))x7&&(x7.token=a),(b=v7())&&b.fx(a)}else b&&y7(),z7(a,1)}else v7()&&y7()},y7=function(){L6()?I6().stopSession():G6("stopSession called before API ready.");
var a=v7();a&&(a.disconnect(1),A7(null))},B7=function(){var a=v7();
return!!a&&3!=a.getProxyState()},p7=function(a){Z5("remote",a)},n7=function(){if(!C7){var a=g.Ha("yt.mdx.remote.screenService_");
C7=a?new k7(a):null}return C7},o7=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},gNa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},hNa=function(){return g.Ha("yt.mdx.remote.connectData_")},r7=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},v7=function(){return g.Ha("yt.mdx.remote.connection_")},A7=function(a){var b=v7();
r7(null);a||gNa("");g.Ga("yt.mdx.remote.connection_",a,void 0);m7&&(g.zb(m7,function(c){c(a)}),m7.length=0);
b&&!a?R4("yt-remote-connection-change",!1):!b&&a&&R4("yt-remote-connection-change",!0)},s7=function(){var a=g.nv();
if(!a)return null;var b=n7();if(!b)return null;b=b.Wg();return Z4(b,a)},z7=function(a,b){o7();
u7()&&u7();D7?x7=a:(gNa(a.id),a=new d7(l7,a,t7()),a.connect(b,hNa()),a.subscribe("beforeDisconnect",function(c){R4("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){v7()&&(v7(),A7(null))}),a.subscribe("browserChannelAuthError",function(){var c=u7();
c&&"shortLived"==c.idType&&(L6()?I6().handleBrowserChannelAuthError():G6("refreshLoungeToken called before API ready."))}),A7(a))},cNa=function(){var a=s7();
a?(p7("Resume connection to: "+V4(a)),z7(a,0)):(d5(),IMa(),p7("Skipping connecting because no session screen found."))},aNa=function(){var a=t7();
if(g.Ob(a)){a=b5();var b=g.kv("yt-remote-session-name")||"",c=g.kv("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},t7=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},E7=function(a,b,c){g.F.call(this);
var d=this;this.l=a;this.I=b;this.Ob=c;this.events=new g.TL(this);this.X=this.events.N(this.I,"onVolumeChange",function(e){iNa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.cJ(64);this.i=new g.J(this.bJ,500,this);this.u=new g.J(this.cJ,1E3,this);this.L=new j5(this.dT,0,this);this.B={};this.V=new g.J(this.IJ,1E3,this);this.J=new k5(this.seekTo,1E3,this);this.Y=g.Ia;g.G(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.bQ);this.events.N(b,"captionschanged",this.oP);this.events.N(b,"captionssettingschanged",this.iJ);this.events.N(b,"videoplayerreset",this.Jw);this.events.N(b,"mdxautoplaycancel",function(){d.Ob.yF()});
a=this.Ob;a.Ga();a.subscribe("proxyStateChange",this.aI,this);a.subscribe("remotePlayerChange",this.gt,this);a.subscribe("remoteQueueChange",this.Jw,this);a.subscribe("previousNextChange",this.XH,this);a.subscribe("nowAutoplaying",this.RH,this);a.subscribe("autoplayDismissed",this.rH,this);g.G(this,this.i);g.G(this,this.u);g.G(this,this.L);g.G(this,this.V);g.G(this,this.J);this.iJ();this.Jw();this.gt()},iNa=function(a,b){if(F7(a)){a.Ob.unsubscribe("remotePlayerChange",a.gt,a);
var c=Math.round(b.volume);b=!!b.muted;var d=X6(a.Ob);if(c!==d.volume||b!==d.muted)a.Ob.setVolume(c,b),a.V.start();a.Ob.subscribe("remotePlayerChange",a.gt,a)}},jNa=function(a){a.Tb(0);
a.i.stop();a.Lb(new g.cJ(64))},G7=function(a,b){if(F7(a)&&!a.C){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.Vb(c,b));a.Ob.WD(a.I.getVideoData(1).videoId,c);a.B=X6(a.Ob).trackData}},H7=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Ob.playVideo(c.videoId,b,d,e,c.playerParams,c.Da,vKa(c));a.Lb(new g.cJ(1))},kNa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{sG:1});
c&&c.length?(a.I.setOption("captions","track",b),a.C=!1):(a.I.loadModule("captions"),a.C=!0)}else a.I.setOption("captions","track",{})},F7=function(a){return X6(a.Ob).videoId===a.I.getVideoData(1).videoId},I7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",oa:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Ca:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],oa:"Learn more"},{D:"button",Ca:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],oa:"OK"}]}]}]});this.i=new g.IK(this,250);this.learnMoreButton=
this.Ba("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Ba("ytp-mdx-manual-pairing-popup-ok");g.G(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},J7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",oa:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",oa:"Videos that you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Ca:["ytp-button","ytp-mdx-privacy-popup-cancel"],oa:"Cancel"},{D:"button",Ca:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],oa:"Confirm"}]}]}]});this.i=new g.IK(this,250);this.cancelButton=this.Ba("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Ba("ytp-mdx-privacy-popup-confirm");g.G(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},K7=function(a){g.V.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.Rma()]},{D:"div",K:"ytp-remote-display-status-text",oa:"{{statustext}}"}]}]});this.api=a;this.i=new g.IK(this,250);g.G(this,this.i);this.N(a,"presentingplayerstatechange",this.l);lNa(this,a.rb())},lNa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.T(b,128)?g.HH("Error on $RECEIVER_NAME",c):b.tc()||g.T(b,4)?g.HH("Playing on $RECEIVER_NAME",c):g.HH("Connected to $RECEIVER_NAME",c);a.Qa("statustext",b);a.i.show()}else a.i.hide()},L7=function(a,b){g.UO.call(this,"Play on",0,a,b);
this.I=a;this.ym={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},M7=function(a){g.dM.call(this,a);
this.ri={key:X4(),name:"This computer"};this.qh=null;this.subscriptions=[];this.EB=this.Ob=null;this.ym=[this.ri];this.Gl=this.ri;this.dd=new g.cJ(64);this.NG=0;this.Qe=-1;this.mq=null;this.ot=this.ew=!1;this.Vk=this.wq=null;if(!g.BD(this.player.T())&&!g.CD(this.player.T())){a=this.player;var b=g.HL(a);b&&(b=b.Ul())&&(b=new L7(a,b),g.G(this,b));b=new K7(a);g.G(this,b);g.RL(a,b.element,4);this.wq=new J7;g.G(this,this.wq);g.RL(a,this.wq.element,4);g.R(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.R(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.mq=new I7,g.G(this,this.mq),g.RL(a,this.mq.element,4));this.ot=!!s7();this.ew=!!g.kv("yt-remote-manual-pairing-warning-shown")}},N7=function(a){a.Vk&&(a.player.removeEventListener("presentingplayerstatechange",a.Vk),a.Vk=null)},mNa=function(a,b,c){a.dd=c;
a.player.W("presentingplayerstatechange",new g.uH(c,b))},nNa=function(a,b,c){var d=!1;
1===b?d=!a.ot:2===b&&(d=!a.ew);d&&g.wH(c,8)&&(a.player.pauseVideo(),N7(a))},O7=function(a,b){if(b.key!==a.Gl.key)if(b.key===a.ri.key)y7();
else{if(a.mq&&!a.ew&&b!==a.ri&&"cast-selector-receiver"!==b.key&&g.XD(a.player.T()))oNa(a);else{var c;(c=!g.R(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.N("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.N("SESSION_INDEX")&&!g.N("LOGGED_IN")))||a.ot||!a.wq);(c?0:g.XD(a.player.T())||g.aE(a.player.T()))&&pNa(a)}a.Gl=b;if(!a.player.T().Z("disable_mdx_connection_in_mdx_module_for_music_web")||!g.CD(a.player.T())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&g.R(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.bb(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Da,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=vKa(c))&&(a.locationInfo=c)}p7("Connecting to: "+
g.xj(b));"cast-selector-receiver"==b.key?(r7(a||null),b=a||null,L6()?I6().setLaunchParams(b):G6("setLaunchParams called before ready.")):!a&&B7()&&o7()==b.key?R4("yt-remote-connection-change",!0):(y7(),r7(a||null),a=n7().Wg(),(b=Z4(a,b.key))&&z7(b,1))}}},pNa=function(a){a.player.rb().tc()?a.player.pauseVideo():(a.Vk=function(b){nNa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Vk));
a.wq&&a.wq.Vc();v7()||(D7=!0)},oNa=function(a){a.player.rb().tc()?a.player.pauseVideo():(a.Vk=function(b){nNa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Vk));
a.mq&&a.mq.Vc();v7()||(D7=!0)},kLa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},z5={"'":"\\'"},EKa={bU:"atp",G3:"ska",x2:"que",D0:"mus",F3:"sus",UX:"dsp",R2:"seq",e0:"mic",UW:"dpa",pU:"cds",B0:"mlm"},e5,a5="",YKa=TKa("loadCastFramework")||TKa("loadCastApplicationFramework"),$Ka=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(j5,g.F);g.k=j5.prototype;g.k.OL=function(a){this.B=arguments;this.i=!1;this.Fb?this.u=g.Ra()+this.Cf:this.Fb=g.Hm(this.C,this.Cf)};
g.k.stop=function(){this.Fb&&(g.B.clearTimeout(this.Fb),this.Fb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.va=function(){this.stop();j5.Jd.va.call(this)};
g.k.PL=function(){this.Fb&&(g.B.clearTimeout(this.Fb),this.Fb=null);this.u?(this.Fb=g.Hm(this.C,this.u-g.Ra()),this.u=null):this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B))};g.v(k5,g.F);g.k=k5.prototype;g.k.PD=function(a){this.u=arguments;this.Fb||this.l?this.i=!0:l5(this)};
g.k.stop=function(){this.Fb&&(g.B.clearTimeout(this.Fb),this.Fb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.Fb||(this.i=!1,l5(this))};
g.k.va=function(){g.F.prototype.va.call(this);this.stop()};n5.prototype.stringify=function(a){return g.B.JSON.stringify(a,void 0)};
n5.prototype.parse=function(a){return g.B.JSON.parse(a,void 0)};var p5=new g.Wl;g.v(bLa,g.xl);r5.prototype.i=null;r5.prototype.getOptions=function(){var a;(a=this.i)||(a={},dLa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var P7;g.Sa(cLa,r5);P7=new cLa;g.k=s5.prototype;g.k.Sm=null;g.k.Li=!1;g.k.Mq=null;g.k.QC=null;g.k.xq=null;g.k.Hq=null;g.k.zl=null;g.k.Am=null;g.k.Io=null;g.k.He=null;g.k.du=0;g.k.Qi=null;g.k.Gx=null;g.k.ul=null;g.k.jr=-1;g.k.TI=!0;g.k.yn=!1;g.k.By=0;g.k.Sw=null;var iLa={},v5={};g.k=s5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.fS=function(a){a=a.target;var b=this.Sw;b&&3==E5(a)?b.PD():this.PJ(a)};
g.k.PJ=function(a){try{if(a==this.He)a:{var b=E5(this.He),c=this.He.G,d=this.He.getStatus();if(g.xe&&!g.be(10)||g.ze&&!g.ae("420+")){if(4>b)break a}else if(3>b||3==b&&!g.lg&&!G5(this.He))break a;this.yn||4!=b||7==c||(8==c||0>=d?this.i.zi(3):this.i.zi(2));A5(this);var e=this.He.getStatus();this.jr=e;var f=G5(this.He);(this.Li=200==e)?(4==b&&x5(this),this.G?(jLa(this,b,f),g.lg&&this.Li&&3==b&&(this.B.Pa(this.u,"tick",this.aS),this.u.start())):w5(this,f),this.Li&&!this.yn&&(4==b?this.i.Au(this):(this.Li=
!1,u5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ul=3,q5(13)):(this.ul=0,q5(14)),x5(this),y5(this))}}catch(h){this.He&&G5(this.He)}finally{}};
g.k.aS=function(){var a=E5(this.He),b=G5(this.He);this.du<b.length&&(A5(this),jLa(this,a,b),this.Li&&4!=a&&u5(this))};
g.k.ER=function(a){o5((0,g.C)(this.DR,this,a),0)};
g.k.DR=function(a){this.yn||(A5(this),w5(this,a),u5(this))};
g.k.iI=function(a){o5((0,g.C)(this.CR,this,a),0)};
g.k.CR=function(a){this.yn||(x5(this),this.Li=a,this.i.Au(this),this.i.zi(4))};
g.k.cancel=function(){this.yn=!0;x5(this)};
g.k.MR=function(){this.Mq=null;var a=Date.now();0<=a-this.QC?(2!=this.Hq&&this.i.zi(3),x5(this),this.ul=2,q5(18),y5(this)):mLa(this,this.QC-a)};
g.k.getLastError=function(){return this.ul};g.Sa(C5,g.Wl);var tLa=/^https?$/i,qNa=["POST","PUT"];g.k=C5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.V+"; newUri="+a);b=b?b.toUpperCase():"GET";this.V=a;this.u="";this.G=0;this.Fa=b;this.xa=!1;this.B=!0;this.i=this.ra?eLa(this.ra):eLa(P7);this.ma=this.ra?this.ra.getOptions():P7.getOptions();this.i.onreadystatechange=(0,g.C)(this.YH,this);try{Q4(F5(this,"Opening Xhr")),this.Aa=!0,this.i.open(b,String(a),!0),this.Aa=!1}catch(f){Q4(F5(this,"Error opening Xhr: "+f.message));sLa(this,f);return}a=
c||"";var e=this.headers.clone();d&&AKa(d,function(f,h){e.set(h,f)});
d=g.cb(e.Bh(),qLa);c=g.B.FormData&&a instanceof g.B.FormData;!g.fb(qNa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.La&&(this.i.responseType=this.La);"withCredentials"in this.i&&this.i.withCredentials!==this.Da&&(this.i.withCredentials=this.Da);try{vLa(this),0<this.J&&(this.Y=pLa(this.i),Q4(F5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.C)(this.QD,this)):this.X=g.Hm(this.QD,this.J,this)),Q4(F5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){Q4(F5(this,"Send error: "+f.message)),sLa(this,f)}};
g.k.QD=function(){"undefined"!=typeof g.h0&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.G=8,F5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(F5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),D5(this))};
g.k.va=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),D5(this,!0));C5.Jd.va.call(this)};
g.k.YH=function(){this.Ga()||(this.Aa||this.L||this.C?uLa(this):this.LQ())};
g.k.LQ=function(){uLa(this)};
g.k.isActive=function(){return!!this.i};
g.k.Nd=function(){return 4==E5(this)};
g.k.getStatus=function(){try{return 2<E5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.Nd())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=wLa.prototype;g.k.Cy=null;g.k.Jg=null;g.k.Tw=!1;g.k.dJ=null;g.k.Zu=null;g.k.SA=null;g.k.Dy=null;g.k.eb=null;g.k.ek=-1;g.k.lr=null;g.k.Dr=null;g.k.connect=function(a){this.Dy=a;a=H5(this.i,null,this.Dy);q5(3);this.dJ=Date.now();var b=this.i.J;null!=b?(this.lr=b[0],(this.Dr=b[1])?(this.eb=1,xLa(this)):(this.eb=2,J5(this))):(O4(a,"MODE","init"),this.Jg=new s5(this,void 0,void 0,void 0),this.Jg.Sm=this.Cy,t5(this.Jg,a,!1,null,!0),this.eb=0)};
g.k.JM=function(a){if(a)this.eb=2,J5(this);else{q5(4);var b=this.i;b.nj=b.El.ek;Q5(b,9)}a&&this.zi(2)};
g.k.Hz=function(a){return this.i.Hz(a)};
g.k.abort=function(){this.Jg&&(this.Jg.cancel(),this.Jg=null);this.ek=-1};
g.k.RD=function(){return!1};
g.k.bI=function(a,b){this.ek=a.jr;if(0==this.eb)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.nj=this.ek;Q5(a,2);return}this.lr=c[0];this.Dr=c[1]}else a=this.i,a.nj=this.ek,Q5(a,2);else if(2==this.eb)if(this.Tw)q5(7),this.SA=Date.now();else if("11111"==b){if(q5(6),this.Tw=!0,this.Zu=Date.now(),a=this.Zu-this.dJ,!g.xe||g.be(10)||500>a)this.ek=200,this.Jg.cancel(),q5(12),I5(this.i,this,!0)}else q5(8),this.Zu=this.SA=Date.now(),this.Tw=!1};
g.k.Au=function(){this.ek=this.Jg.jr;if(this.Jg.Li)0==this.eb?this.Dr?(this.eb=1,xLa(this)):(this.eb=2,J5(this)):2==this.eb&&((!g.xe||g.be(10)?!this.Tw:200>this.SA-this.Zu)?(q5(11),I5(this.i,this,!1)):(q5(12),I5(this.i,this,!0)));else{0==this.eb?q5(9):2==this.eb&&q5(10);var a=this.i;this.Jg.getLastError();a.nj=this.ek;Q5(a,2)}};
g.k.Kt=function(){return this.i.Kt()};
g.k.isActive=function(){return this.i.isActive()};
g.k.zi=function(a){this.i.zi(a)};g.k=K5.prototype;g.k.mj=null;g.k.Tr=null;g.k.xg=null;g.k.Yd=null;g.k.Ey=null;g.k.bv=null;g.k.UE=null;g.k.Bu=null;g.k.Ts=0;g.k.KO=0;g.k.xf=null;g.k.Ll=null;g.k.wk=null;g.k.Gn=null;g.k.El=null;g.k.Ex=null;g.k.hq=-1;g.k.MG=-1;g.k.nj=-1;g.k.Qp=0;g.k.Ep=0;g.k.zn=8;g.Sa(zLa,g.xl);g.Sa(ALa,g.xl);g.k=K5.prototype;g.k.connect=function(a,b,c,d,e){q5(0);this.Ey=b;this.Tr=c||{};d&&void 0!==e&&(this.Tr.OSID=d,this.Tr.OAID=e);this.C?(o5((0,g.C)(this.lF,this,a),100),ELa(this)):this.lF(a)};
g.k.lF=function(a){this.El=new wLa(this);this.El.Cy=this.mj;this.El.l=this.B;this.El.connect(a)};
g.k.RD=function(){return 0==this.eb};
g.k.getState=function(){return this.eb};
g.k.gI=function(a){this.Ll=null;ILa(this,a)};
g.k.fI=function(){this.wk=null;this.Yd=new s5(this,this.l,"rpc",this.G);this.Yd.Sm=this.mj;this.Yd.By=0;var a=this.UE.clone();M4(a,"RID","rpc");M4(a,"SID",this.l);M4(a,"CI",this.Ex?"0":"1");M4(a,"AID",this.hq);L5(this,a);if(!g.xe||g.be(10))M4(a,"TYPE","xmlhttp"),t5(this.Yd,a,!0,this.Bu,!1);else{M4(a,"TYPE","html");var b=this.Yd,c=!!this.Bu;b.Hq=3;b.zl=N4(a.clone());lLa(b,c)}};
g.k.bI=function(a,b){if(0!=this.eb&&(this.Yd==a||this.xg==a))if(this.nj=a.jr,this.xg==a&&3==this.eb)if(7<this.zn){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.wk){if(this.Yd)if(this.Yd.xq+3E3<this.xg.xq)N5(this),this.Yd.cancel(),this.Yd=null;else break a;P5(this);q5(19)}}else this.MG=a[1],0<this.MG-this.hq&&37500>a[2]&&this.Ex&&0==this.Ep&&!this.Gn&&(this.Gn=o5((0,g.C)(this.lP,this),6E3));else Q5(this,11)}else null!=b&&Q5(this,11);else if(this.Yd==
a&&N5(this),!g.nc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.hq=c[0],c=c[1],2==this.eb?"c"==c[0]?(this.l=c[1],this.Bu=c[2],c=c[3],null!=c?this.zn=c:this.zn=6,this.eb=3,this.xf&&this.xf.hF(),this.UE=H5(this,this.Kt()?this.Bu:null,this.Ey),JLa(this)):"stop"==c[0]&&Q5(this,7):3==this.eb&&("stop"==c[0]?Q5(this,7):"noop"!=c[0]&&this.xf&&this.xf.gF(c),this.Ep=0)};
g.k.lP=function(){null!=this.Gn&&(this.Gn=null,this.Yd.cancel(),this.Yd=null,P5(this),q5(20))};
g.k.Au=function(a){if(this.Yd==a){N5(this);this.Yd=null;var b=2}else if(this.xg==a)this.xg=null,b=1;else return;this.nj=a.jr;if(0!=this.eb)if(a.Li)1==b?(b=p5,b.dispatchEvent(new zLa(b,a.Io?a.Io.length:0,Date.now()-a.xq,this.Qp)),M5(this),this.u.length=0):JLa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.nj)){if(d=1==b)this.xg||this.Ll||1==this.eb||2<=this.Qp?d=!1:(this.Ll=o5((0,g.C)(this.gI,this,a),KLa(this,this.Qp)),this.Qp++,d=!0);d=!(d||2==b&&P5(this))}if(d)switch(c){case 1:Q5(this,
5);break;case 4:Q5(this,10);break;case 3:Q5(this,6);break;case 7:Q5(this,12);break;default:Q5(this,2)}}};
g.k.hN=function(a){if(!g.fb(arguments,this.eb))throw Error("Unexpected channel state: "+this.eb);};
g.k.KS=function(a){a?q5(2):(q5(1),LLa(this,8))};
g.k.Hz=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new C5;a.Da=!1;return a};
g.k.isActive=function(){return!!this.xf&&this.xf.isActive(this)};
g.k.zi=function(a){var b=p5;b.dispatchEvent(new ALa(b,a))};
g.k.Kt=function(){return!(!g.xe||g.be(10))};
g.k=MLa.prototype;g.k.hF=function(){};
g.k.gF=function(){};
g.k.fF=function(){};
g.k.rz=function(){};
g.k.NF=function(){return{}};
g.k.isActive=function(){return!0};g.k=NLa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.dFa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.zg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Sa(R5,g.F);g.k=R5.prototype;g.k.wR=function(){this.Cf=Math.min(3E5,2*this.Cf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Cf+15E3*Math.random();g.gn(this.i,a);this.l=g.Ra()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Cf=5E3};g.Sa(S5,MLa);g.k=S5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.If=function(a){return this.u.If(a)};
g.k.W=function(a,b){return this.u.W.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.xi(this.u),QLa(this),g.xi(this.l),this.l=null,this.Y=function(){return""})};
g.k.Ga=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ma+"/test";b=this.ma+"/bind";var d=new K5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ra),e=this.i;e&&(e.xf=null);d.xf=this;this.i=d;T5(this);if(this.i){d=g.N("ID_TOKEN");var f=this.i.mj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.mj=f}e?(3!=e.getState()&&0==GLa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.hq)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Vb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):U5(this)&&(T5(this),FLa(this.i,a))};
g.k.hF=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)FLa(this.i,a[b])}this.W("handlerOpened")};
g.k.fF=function(a){var b=2==a&&401==this.i.nj;4==a||b||this.l.start();this.W("handlerError",a,b)};
g.k.rz=function(a){if(!this.l.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.NF=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Vb(a,this.C);return a};
g.k.gF=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),DLa(this.i)):this.W("handlerMessage",new OLa(a[0],a[1]))};
g.k.fx=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.xa&&this.i){var b=this.i.mj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.mj=b}};
g.k.qS=function(){this.l.isActive();0==GLa(this.i)&&this.connect(this.C,this.B)};V5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
V5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
V5.prototype.C=function(a){a(Error("request timed out"))};var XLa=Date.now(),Y5=null,a6=Array(50),$5=-1,b6=!1;g.Sa(c6,g.P);c6.prototype.Wg=function(){return this.screens};
c6.prototype.contains=function(a){return!!Y4(this.screens,a)};
c6.prototype.get=function(a){return a?Z4(this.screens,a):null};
c6.prototype.info=function(a){Z5(this.G,a)};g.v(d6,g.P);g.k=d6.prototype;g.k.start=function(){!this.i&&isNaN(this.Fb)&&this.pI()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Fb)||(g.op(this.Fb),this.Fb=NaN)};
g.k.va=function(){this.stop();g.P.prototype.va.call(this)};
g.k.pI=function(){this.Fb=NaN;this.i=g.tp(W5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.RL,this),onError:(0,g.C)(this.QL,this),onTimeout:(0,g.C)(this.SL,this)})};
g.k.RL=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.G;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.W("pairingComplete",new T4(a),b)};
g.k.QL=function(a){this.i=null;a.status&&404==a.status?this.l>=rNa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=rNa[this.l],this.Fb=g.mp((0,g.C)(this.pI,this),a),this.l++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.SL=function(){this.i=null;this.W("pairingFailed",Error("Server not responding"))};
var rNa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(f6,c6);g.k=f6.prototype;g.k.start=function(){e6(this)&&this.W("screenChange");!g.kv("yt-remote-lounge-token-expiration")&&aMa(this);g.op(this.i);this.i=g.mp((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){e6(this);YLa(this,a);g6(this,!1);this.W("screenChange");b(a);a.token||aMa(this)};
g.k.remove=function(a,b){var c=e6(this);$La(this,a)&&(g6(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.Cx=function(a,b,c,d){var e=e6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,g6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.va=function(){g.op(this.i);f6.Jd.va.call(this)};
g.k.FN=function(a){e6(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}g6(this,!b);b&&Z5(this.G,"Missed "+b+" lounge tokens.")};
g.k.EN=function(a){Z5(this.G,"Requesting lounge tokens failed: "+a)};g.v(i6,g.P);g.k=i6.prototype;g.k.start=function(){var a=parseInt(g.kv("yt-remote-fast-check-period")||"0",10);(this.B=g.Ra()-144E5<a?0:a)?l6(this):(this.B=g.Ra()+3E5,g.jv("yt-remote-fast-check-period",this.B),this.RB())};
g.k.isEmpty=function(){return g.Ob(this.i)};
g.k.update=function(){h6("Updating availability on schedule.");var a=this.G(),b=g.Cb(this.i,function(c,d){return c&&!!Z4(a,d)},this);
k6(this,b)};
g.k.va=function(){g.op(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.P.prototype.va.call(this)};
g.k.RB=function(){g.op(this.u);this.u=NaN;this.l&&this.l.abort();var a=cMa(this);if(P4(a)){var b=W5(this.C,"/pairing/get_screen_availability");this.l=X5(this.C,b,{lounge_token:g.Jb(a).join(",")},(0,g.C)(this.fR,this,a),(0,g.C)(this.eR,this))}else k6(this,{}),l6(this)};
g.k.fR=function(a,b){this.l=null;var c=g.Jb(cMa(this));if(g.xb(c,g.Jb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;k6(this,c);l6(this)}else this.Kd("Changing Screen set during request."),this.RB()};
g.k.eR=function(a){this.Kd("Screen availability failed: "+a);this.l=null;l6(this)};
g.k.Kd=function(a){Z5("OnlineScreenService",a)};g.Sa(m6,c6);g.k=m6.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.W("screenChange"),this.i.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Cx=function(a,b,c,d){this.l.contains(a)?this.l.Cx(a,b,c,d):(a="Updating name of unknown screen: "+a.name,Z5(this.G,a),d(Error(a)))};
g.k.Wg=function(a){return a?this.screens:g.nb(this.screens,g.Je(this.u,function(b){return!this.contains(b)},this))};
g.k.SD=function(){return g.Je(this.Wg(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.TD=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new d6(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.xi(l);e(n6(h,m),n)});
l.subscribe("pairingFailed",function(m){g.xi(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.TL=function(a,b,c,d){g.tp(W5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){e=new T4(f.screen||{});if(!e.name||gMa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);gMa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(n6(this,e))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.xi(this.l);g.xi(this.i);m6.Jd.va.call(this)};
g.k.LN=function(){iMa(this);this.W("screenChange");this.i.update()};
m6.prototype.dispose=m6.prototype.dispose;g.Sa(p6,g.P);g.k=p6.prototype;g.k.getScreen=function(){return this.B};
g.k.Yf=function(a){this.Ga()||(a&&r6(this,""+a),this.B=null,this.W("sessionScreen",null))};
g.k.info=function(a){Z5(this.xa,a)};
g.k.UD=function(){return null};
g.k.bC=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){r6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.bC("");p6.Jd.va.call(this)};g.v(s6,p6);g.k=s6.prototype;g.k.aC=function(a){if(this.l){if(this.l==a)return;r6(this,"Overriding cast session with new session object");rMa(this);this.ma=!1;this.V="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra);nMa(this,"getMdxSessionStatus")};
g.k.iq=function(a){this.info("launchWithParams no-op for Cast: "+g.xj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.Yf()},this),(0,g.C)(function(){this.Yf(Error("Failed to stop receiver app."))},this)):this.Yf(Error("Stopping cast device without session."))};
g.k.bC=function(){};
g.k.va=function(){this.info("disposeInternal");rMa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra));this.l=null;p6.prototype.va.call(this)};
g.k.PR=function(a,b){if(!this.Ga())if(b)if(b=m5(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.xj(b)),a){case "mdxSessionStatus":lMa(this,b);break;case "loungeToken":oMa(this,b);break;default:r6(this,"Unknown youtube message: "+a)}else r6(this,"Unable to parse message.");else r6(this,"No data in message.")};
g.k.bG=function(a,b,c,d){g.op(this.L);this.L=0;fMa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(r6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.mp((0,g.C)(this.bG,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.UD=function(){return this.l};
g.k.UL=function(a){this.Ga()||a||(r6(this,"Cast session died."),this.Yf())};g.v(v6,p6);g.k=v6.prototype;g.k.aC=function(a){this.l=a;this.l.addUpdateListener(this.Aa)};
g.k.iq=function(a){this.Ea=a;this.X()};
g.k.stop=function(){yMa(this);this.l?this.l.stop((0,g.C)(this.Yf,this,null),(0,g.C)(this.Yf,this,"Failed to stop DIAL device.")):this.Yf()};
g.k.va=function(){yMa(this);this.l&&this.l.removeUpdateListener(this.Aa);this.l=null;p6.prototype.va.call(this)};
g.k.VL=function(a){this.Ga()||a||(r6(this,"DIAL session died."),this.C(),this.C=g.Ia,this.Yf())};g.v(z6,p6);z6.prototype.stop=function(){this.Yf()};
z6.prototype.aC=function(){};
z6.prototype.iq=function(){g.op(this.l);this.l=NaN;var a=Z4(this.u.Wg(),this.i.label);a?q6(this,a):this.Yf(Error("No such screen"))};
z6.prototype.va=function(){g.op(this.l);this.l=NaN;p6.prototype.va.call(this)};g.v(A6,g.P);g.k=A6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.J);this.L||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.V?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.C)(this.PQ,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.cI,this),e,d,a);c.customDialLaunchCallback=(0,g.C)(this.FP,this);chrome.cast.initialize(c,(0,g.C)(function(){this.Ga()||
(chrome.cast.addReceiverActionListener(this.C),ULa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.VD,this)),this.u=AMa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(f){this.Kd("Failed to set initial custom receivers: "+g.xj(f))},this)),this.W("yt-remote-cast2-availability-change",C6(this)),b(!0))},this),(0,g.C)(function(f){this.Kd("Failed to initialize API: "+g.xj(f));
b(!1)},this))};
g.k.vS=function(a,b){B6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)B6("Unsetting old screen status: "+this.i.i.friendlyName),D6(this,null)}if(a&&b){if(!this.i){c=Z4(this.l.Wg(),a);if(!c){B6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){B6("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=zMa(this,c);a||(B6("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(d){this.Kd("Failed to set initial custom receivers: "+g.xj(d))},this)));
B6("setConnectedScreenStatus: new active receiver: "+a.friendlyName);D6(this,new z6(this.l,a),!0)}this.i.bC(b)}else B6("setConnectedScreenStatus: no screen.")};
g.k.wS=function(a){this.Ga()?this.Kd("Setting connection data on disposed cast v2"):this.i?this.i.iq(a):this.Kd("Setting connection data without a session")};
g.k.XL=function(){this.Ga()?this.Kd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),D6(this,null)):B6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.cI,this),(0,g.C)(this.iR,this))};
g.k.va=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.VD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);var a=RLa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.xi(this.i);g.P.prototype.va.call(this)};
g.k.Kd=function(a){Z5("Controller",a)};
g.k.eI=function(a,b){this.i==a&&(b||D6(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.MQ=function(a,b){if(!this.Ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),B6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)B6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{B6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.W("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:D6(this,
new z6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:D6(this,new v6(this.l,a,this.B,this.config_));break;case chrome.cast.ReceiverType.CAST:D6(this,new s6(this.l,a,this.config_));break;default:this.Kd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Kd("Stopping receiver w/o session: "+a.friendlyName)}else this.Kd("onReceiverAction_ called without receiver.")};
g.k.FP=function(a){if(this.Ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Kd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Kd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return B6("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Kd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);D6(this,new v6(this.l,b,this.B,this.config_))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,w6(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=vMa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.So(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=wMa(b,c)):a=wMa(b,c)):a=y6(b);return a};
g.k.cI=function(a){if(!this.Ga()){B6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)B6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),D6(this,new s6(this.l,b,this.config_),!0);else{this.Kd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=Z4(this.l.Wg(),c.label);d&&U4(d,
b.label)&&c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(B6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.xi(this.i),this.i=new s6(this.l,b,this.config_),this.i.subscribe("sessionScreen",(0,g.C)(this.eI,this,this.i)),this.i.iq(null));this.i.aC(a)}}};
g.k.WL=function(){return this.i?this.i.UD():null};
g.k.iR=function(a){this.Ga()||(this.Kd("Failed to estabilish a session: "+g.xj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&D6(this,null))};
g.k.PQ=function(a){B6("Receiver availability updated: "+a);if(!this.Ga()){var b=C6(this);this.G=a==chrome.cast.ReceiverAvailability.AVAILABLE;C6(this)!=b&&this.W("yt-remote-cast2-availability-change",C6(this))}};
g.k.VD=function(){this.Ga()||(this.u=AMa(this),B6("Updating custom receivers: "+g.xj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(){this.Kd("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",C6(this)))};
A6.prototype.setLaunchParams=A6.prototype.wS;A6.prototype.setConnectedScreenStatus=A6.prototype.vS;A6.prototype.stopSession=A6.prototype.XL;A6.prototype.getCastSession=A6.prototype.WL;A6.prototype.requestSession=A6.prototype.requestSession;A6.prototype.init=A6.prototype.init;A6.prototype.dispose=A6.prototype.dispose;var J6=[];g.k=O6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";P6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Cj=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.G=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.tc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.l?this.C+Q6(this):this.C};
g.k.clone=function(){return new O6(U6(this))};g.v(W6,g.P);g.k=W6.prototype;g.k.getState=function(){return this.eb};
g.k.play=function(){Y6(this)?(this.i?this.i.play(null,g.Ia,c7(this,"play")):b7(this,"play"),a7(this,1,S6(X6(this))),this.W("remotePlayerChange")):Z6(this,this.play)};
g.k.pause=function(){Y6(this)?(this.i?this.i.pause(null,g.Ia,c7(this,"pause")):b7(this,"pause"),a7(this,2,S6(X6(this))),this.W("remotePlayerChange")):Z6(this,this.pause)};
g.k.seekTo=function(a){if(Y6(this)){if(this.i){var b=X6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.tc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,c7(this,"seekTo",{newTime:a}))}else b7(this,"seekTo",{newTime:a});a7(this,3,a);this.W("remotePlayerChange")}else Z6(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(Y6(this)){this.i?this.i.stop(null,g.Ia,c7(this,"stopVideo")):b7(this,"stopVideo");var a=X6(this);a.index=-1;a.videoId="";P6(a);$6(this,a);this.W("remotePlayerChange")}else Z6(this,this.stop)};
g.k.setVolume=function(a,b){if(Y6(this)){var c=X6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){Z5("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Kd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){Z5("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Kd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);b7(this,"setVolume",e)}c.muted=b;c.volume=a;$6(this,c)}else Z6(this,g.Pa(this.setVolume,a,b))};
g.k.WD=function(a,b){if(Y6(this)){var c=X6(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.xj(b.style),g.Vb(a,c.trackData));b7(this,"setSubtitlesTrack",a);$6(this,c)}else Z6(this,g.Pa(this.WD,a,b))};
g.k.setAudioTrack=function(a,b){Y6(this)?(b=b.getLanguageInfo().getId(),b7(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=X6(this),a.audioTrackId=b,$6(this,a)):Z6(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=X6(this);c=c||0;var m={videoId:a,currentIndex:c};T6(l,a,c);void 0!==b&&(R6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.xj(h));b7(this,"setPlaylist",m);d||$6(this,l)};
g.k.Ow=function(a,b){if(Y6(this)){if(a&&b){var c=X6(this);T6(c,a,b);$6(this,c)}b7(this,"previous")}else Z6(this,g.Pa(this.Ow,a,b))};
g.k.nextVideo=function(a,b){if(Y6(this)){if(a&&b){var c=X6(this);T6(c,a,b);$6(this,c)}b7(this,"next")}else Z6(this,g.Pa(this.nextVideo,a,b))};
g.k.yF=function(){Y6(this)?b7(this,"dismissAutoplay"):Z6(this,this.yF)};
g.k.dispose=function(){if(3!=this.eb){var a=this.eb;this.eb=3;this.W("proxyStateChange",a,this.eb)}g.P.prototype.dispose.call(this)};
g.k.va=function(){MMa(this);this.u=null;this.B.clear();V6(this,null);g.P.prototype.va.call(this)};
g.k.dC=function(a){if((a!=this.eb||2==a)&&3!=this.eb&&0!=a){var b=this.eb;this.eb=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.JQ=function(a,b){this.W(a,b)};
g.k.rP=function(a){if(!a)this.Ws(null),V6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=X6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Z5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,$6(this,b)}};
g.k.Ws=function(a){Z5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),NMa(this),this.W("remotePlayerChange")};
g.k.qP=function(a){a?(NMa(this),this.W("remotePlayerChange")):this.Ws(null)};
g.k.uC=function(){b7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.yP=function(){var a=JMa();a&&V6(this,a)};
g.k.Kd=function(a){Z5("CP",a)};g.v(d7,g.P);g.k=d7.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime;b=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);b&&(l.locationInfo=b);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.dc.listId=c);this.dc.videoId=d;this.dc.index=h||0;this.dc.state=3;R6(this.dc,m);this.B="UNSUPPORTED";e7("Connecting with setPlaylist and params: "+g.xj(l));this.i.connect({method:"setPlaylist",
params:g.xj(l)},a,MKa())}else e7("Connecting without params"),this.i.connect({},a,MKa());PMa(this)};
g.k.fx=function(a){this.i.fx(a)};
g.k.dispose=function(){this.Ga()||(this.W("beforeDispose"),f7(this,3));g.P.prototype.dispose.call(this)};
g.k.va=function(){g7(this);i7(this);h7(this);g.op(this.J);this.J=NaN;g.op(this.L);this.L=NaN;this.u=null;g.Tp(this.V);this.V.length=0;this.i.dispose();g.P.prototype.va.call(this);this.B=this.G=this.l=this.dc=this.i=null};
g.k.BN=function(){this.Mp(2)};
g.k.vP=function(){e7("Channel opened");this.ma&&(this.ma=!1,h7(this),this.Y=g.mp((0,g.C)(function(){e7("Timing out waiting for a screen.");this.Mp(1)},this),15E3));
QKa(PLa(this.i),this.Aa)};
g.k.sP=function(){e7("Channel closed");isNaN(this.C)?d5(!0):d5();this.dispose()};
g.k.tP=function(a,b){d5();isNaN(this.ws())?(b&&"shortLived"==this.ra&&this.W("browserChannelAuthError",a),e7("Channel error: "+a+" without reconnection"),this.dispose()):(this.ma=!0,e7("Channel error: "+a+" with reconnection in "+this.ws()+" ms"),f7(this,2))};
g.k.uP=function(a){a.params?e7("Received: action="+a.action+", params="+g.xj(a.params)):e7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=m5(a.params.devices);this.l=g.Mc(a,function(c){return new S4(c)});
a=!!g.cb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
SMa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
SMa(this,!1);break;case "remoteConnected":var b=new S4(m5(a.params.device));g.cb(this.l,function(c){return b?c.id==b.id:!1})||wKa(this.l,b);
break;case "remoteDisconnected":b=new S4(m5(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":UMa(this,a);break;case "nowPlaying":WMa(this,a);break;case "onStateChange":VMa(this,a);break;case "onAdStateChange":XMa(this,a);break;case "onVolumeChanged":YMa(this,a);break;case "onSubtitlesTrackChanged":TMa(this,a);break;case "nowAutoplaying":ZMa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.W("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.W("autoplayModeChange",this.B);"DISABLED"==this.B&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":$Ma(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:e7("Unrecognized action: "+a.action)}};
g.k.mS=function(){if(this.u){var a=this.u;this.u=null;this.dc.videoId!=a&&j7(this,"getNowPlaying")}};
g.k.wN=function(){var a=3;this.Ga()||(a=0,isNaN(this.ws())?U5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Mp=function(a){e7("Disconnecting with "+a);g7(this);this.W("beforeDisconnect",a);1==a&&d5();QLa(this.i,a);this.dispose()};
g.k.uN=function(){var a=this.dc;this.u&&(a=this.dc.clone(),T6(a,this.u,a.index));return U6(a)};
g.k.xS=function(a){var b=new O6(a);b.videoId&&b.videoId!=this.dc.videoId&&(this.u=b.videoId,g.op(this.J),this.J=g.mp((0,g.C)(this.mS,this),5E3));var c=[];this.dc.listId==b.listId&&this.dc.videoId==b.videoId&&this.dc.index==b.index||c.push("remoteQueueChange");this.dc.playerState==b.playerState&&this.dc.volume==b.volume&&this.dc.muted==b.muted&&S6(this.dc)==S6(b)&&g.xj(this.dc.trackData)==g.xj(b.trackData)||c.push("remotePlayerChange");this.dc.reset(a);g.zb(c,function(d){this.W(d)},this)};
g.k.ZF=function(){var a=this.i.G.id,b=g.cb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.ws=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Ra():NaN};
g.k.sN=function(){return this.B||"UNSUPPORTED"};
g.k.tN=function(){return this.G||""};
g.k.YL=function(){if(!isNaN(this.ws())){var a=this.i.l;g.hn(a.i);a.start()}};
g.k.uS=function(a,b){j7(this,a,b);RMa(this)};
g.k.XD=function(){var a=g.Do("SID","")||"",b=g.Do("SAPISID","")||"",c=g.Do("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.uf(g.Xe(a),2);b=g.uf(g.Xe(b),2);c=g.uf(g.Xe(c),2);return g.uf(g.Xe(a+","+b+","+c),2)};
d7.prototype.subscribe=d7.prototype.subscribe;d7.prototype.unsubscribeByKey=d7.prototype.If;d7.prototype.getProxyState=d7.prototype.wN;d7.prototype.disconnect=d7.prototype.Mp;d7.prototype.getPlayerContextData=d7.prototype.uN;d7.prototype.setPlayerContextData=d7.prototype.xS;d7.prototype.getOtherConnectedRemoteId=d7.prototype.ZF;d7.prototype.getReconnectTimeout=d7.prototype.ws;d7.prototype.getAutoplayMode=d7.prototype.sN;d7.prototype.getAutoplayVideoId=d7.prototype.tN;d7.prototype.reconnect=d7.prototype.YL;
d7.prototype.sendMessage=d7.prototype.uS;d7.prototype.getXsrfToken=d7.prototype.XD;g.v(k7,c6);g.k=k7.prototype;g.k.Wg=function(a){return this.Bf.$_gs(a)};
g.k.contains=function(a){return!!this.Bf.$_c(a)};
g.k.get=function(a){return this.Bf.$_g(a)};
g.k.start=function(){this.Bf.$_st()};
g.k.add=function(a,b,c){this.Bf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Bf.$_r(a,b,c)};
g.k.Cx=function(a,b,c,d){this.Bf.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.Bf.$_ubk(this.i[a]);this.i.length=0;this.Bf=null;c6.prototype.va.call(this)};
g.k.ZL=function(){this.W("screenChange")};
g.k.qQ=function(){this.W("onlineScreenChange")};
m6.prototype.$_st=m6.prototype.start;m6.prototype.$_gspc=m6.prototype.TL;m6.prototype.$_gsppc=m6.prototype.TD;m6.prototype.$_c=m6.prototype.contains;m6.prototype.$_g=m6.prototype.get;m6.prototype.$_a=m6.prototype.add;m6.prototype.$_un=m6.prototype.Cx;m6.prototype.$_r=m6.prototype.remove;m6.prototype.$_gs=m6.prototype.Wg;m6.prototype.$_gos=m6.prototype.SD;m6.prototype.$_s=m6.prototype.subscribe;m6.prototype.$_ubk=m6.prototype.If;var x7=null,D7=!1,l7=null,m7=null,C7=null,q7=[];g.v(E7,g.F);g.k=E7.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.Ob;a.unsubscribe("proxyStateChange",this.aI,this);a.unsubscribe("remotePlayerChange",this.gt,this);a.unsubscribe("remoteQueueChange",this.Jw,this);a.unsubscribe("previousNextChange",this.XH,this);a.unsubscribe("nowAutoplaying",this.RH,this);a.unsubscribe("autoplayDismissed",this.rH,this);this.Ob=this.l=null};
g.k.YD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Ob.eb)if(F7(this)){if(!X6(this.Ob).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":X6(this.Ob).tc()?this.Ob.pause():this.Ob.play();break;case "control_play":this.Ob.play();break;case "control_pause":this.Ob.pause();break;case "control_seek":this.J.PD(c[0],c[1]);break;case "control_subtitles_set_track":G7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();H7(this,0===c?void 0:c);break;case "control_seek":H7(this,c[0]);break;case "control_subtitles_set_track":G7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.oP=function(a){this.L.OL(a)};
g.k.dT=function(a){this.YD("control_subtitles_set_track",g.Ob(a)?null:a)};
g.k.iJ=function(){var a=this.I.getOption("captions","track");g.Ob(a)||G7(this,a)};
g.k.Tb=function(a){this.l.Tb(a,this.I.getVideoData().lengthSeconds)};
g.k.bQ=function(){g.Ob(this.B)||kNa(this,this.B);this.C=!1};
g.k.aI=function(a,b){this.u.stop();2===b&&this.cJ()};
g.k.gt=function(){if(F7(this)){this.i.stop();var a=X6(this.Ob);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Qe=1;break;case 1082:case 1083:this.l.Qe=0;break;default:this.l.Qe=-1}switch(a.playerState){case 1081:case 1:this.Lb(new g.cJ(8));this.bJ();break;case 1085:case 3:this.Lb(new g.cJ(9));break;case 1083:case 0:this.Lb(new g.cJ(2));this.J.stop();this.Tb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Lb(new g.cJ(4));break;case 2:this.Lb(new g.cJ(4));this.Tb(S6(a));
break;case -1:this.Lb(new g.cJ(64));break;case -1E3:this.Lb(new g.cJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=X6(this.Ob).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,kNa(this,a));a=X6(this.Ob);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.V.isActive()||this.IJ()}else jNa(this)};
g.k.XH=function(){this.I.W("mdxpreviousnextchange")};
g.k.Jw=function(){F7(this)||jNa(this)};
g.k.RH=function(a){isNaN(a)||this.I.W("mdxnowautoplaying",a)};
g.k.rH=function(){this.I.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){F7(this)&&this.Ob.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===X6(this.Ob).playerState?H7(this,a):b&&this.Ob.seekTo(a)};
g.k.IJ=function(){var a=this;if(F7(this)){var b=X6(this.Ob);this.events.fc(this.X);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.X=this.events.N(this.I,"onVolumeChange",function(c){iNa(a,c)})}};
g.k.bJ=function(){this.i.stop();if(!this.Ob.Ga()){var a=X6(this.Ob);a.tc()&&this.Lb(new g.cJ(8));this.Tb(S6(a));this.i.start()}};
g.k.cJ=function(){this.u.stop();this.i.stop();var a=this.Ob.u.getReconnectTimeout();2==this.Ob.eb&&!isNaN(a)&&this.u.start()};
g.k.Lb=function(a){this.u.stop();var b=this.G;if(!g.hJ(b,a)){var c=g.T(a,2);c!==g.T(this.G,2)&&this.I.No(c);this.G=a;mNa(this.l,b,a)}};g.v(I7,g.V);I7.prototype.Vc=function(){this.i.show()};
I7.prototype.Ab=function(){this.i.hide()};
I7.prototype.l=function(){g.KI("https://support.google.com/youtube/answer/7640706")};
I7.prototype.u=function(){R4("mdx-manual-pairing-popup-ok");this.Ab()};g.v(J7,g.V);J7.prototype.Vc=function(){this.i.show()};
J7.prototype.Ab=function(){this.i.hide()};
J7.prototype.l=function(){R4("mdx-privacy-popup-cancel");this.Ab()};
J7.prototype.u=function(){R4("mdx-privacy-popup-confirm");this.Ab()};g.v(K7,g.V);K7.prototype.l=function(a){lNa(this,a.state)};g.v(L7,g.UO);L7.prototype.C=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.ym=g.Ab(a,this.i,this),g.VO(this,g.Mc(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.lh(a),this.enable(!0)):this.enable(!1)};
L7.prototype.i=function(a){return a.key};
L7.prototype.Xh=function(a){return"cast-selector-receiver"===a?"Cast...":this.ym[a].name};
L7.prototype.We=function(a){g.UO.prototype.We.call(this,a);this.I.setOption("remote","currentReceiver",this.ym[a]);this.wb.Ab()};g.v(M7,g.dM);g.k=M7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.zD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.R(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.R(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.R(a.experiments,"enable_cast_short_lived_lounge_token")};dNa(b,a);this.subscriptions.push(g.Rq("yt-remote-before-disconnect",this.nP,this));this.subscriptions.push(g.Rq("yt-remote-connection-change",this.QQ,this));this.subscriptions.push(g.Rq("yt-remote-receiver-availability-change",
this.ZH,this));this.subscriptions.push(g.Rq("yt-remote-auto-connect",this.OQ,this));this.subscriptions.push(g.Rq("yt-remote-receiver-resumed",this.NQ,this));this.subscriptions.push(g.Rq("mdx-privacy-popup-confirm",this.dS,this));this.subscriptions.push(g.Rq("mdx-privacy-popup-cancel",this.cS,this));this.subscriptions.push(g.Rq("mdx-manual-pairing-popup-ok",this.xO,this));this.ZH()};
g.k.load=function(){this.player.cancelPlayback();g.dM.prototype.load.call(this);this.qh=new E7(this,this.player,this.Ob);var a=(a=hNa())?a.currentTime:0;var b=B7()?new W6(v7(),void 0):null;0==a&&b&&(a=S6(X6(b)));0!==a&&this.Tb(a);mNa(this,this.dd,this.dd);this.player.Vj(6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.Gl=this.ri;g.Ci(this.qh,this.Ob);this.Ob=this.qh=null;g.dM.prototype.unload.call(this);this.player.Vj(5);N7(this)};
g.k.va=function(){g.Sq(this.subscriptions);g.dM.prototype.va.call(this)};
g.k.Mj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.qh.YD.apply(this.qh,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Qe};
g.k.xN=function(){return this.loaded?this.qh.suggestion:null};
g.k.Cj=function(){return this.Ob?X6(this.Ob).Cj:!1};
g.k.hasNext=function(){return this.Ob?X6(this.Ob).hasNext:!1};
g.k.Tb=function(a,b){this.NG=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.NG};
g.k.getProgressState=function(){var a=X6(this.Ob),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Pe():!a.isAdPlaying()&&this.player.Pe(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+Q6(a):a.u,isAtLiveHead:1>=(a.l?a.i+Q6(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+Q6(a):a.i,seekableStart:0<a.B?a.B+
Q6(a):a.B}};
g.k.nextVideo=function(){this.Ob&&this.Ob.nextVideo()};
g.k.Ow=function(){this.Ob&&this.Ob.Ow()};
g.k.nP=function(a){1===a&&(this.EB=this.Ob?X6(this.Ob):null)};
g.k.QQ=function(){var a=B7()?new W6(v7(),void 0):null;if(a){var b=this.Gl;this.loaded&&this.unload();this.Ob=a;this.EB=null;b.key!==this.ri.key&&(this.Gl=b,this.load())}else g.xi(this.Ob),this.Ob=null,this.loaded&&(this.unload(),(a=this.EB)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,S6(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.ZH=function(){var a=[this.ri],b=a.concat,c=eNa();K6()&&g.kv("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.ym=b.call(a,c);a=w7()||this.ri;O7(this,a);this.player.Ma("onMdxReceiversChange")};
g.k.OQ=function(){var a=w7();O7(this,a)};
g.k.NQ=function(){this.Gl=w7()};
g.k.dS=function(){this.ot=!0;N7(this);D7=!1;x7&&z7(x7,1);x7=null};
g.k.cS=function(){this.ot=!1;N7(this);O7(this,this.ri);this.Gl=this.ri;D7=!1;x7=null;this.player.playVideo()};
g.k.xO=function(){this.ew=!0;N7(this);g.jv("yt-remote-manual-pairing-warning-shown",!0,2592E3);D7=!1;x7&&z7(x7,1);x7=null};
g.k.Je=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.ym;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?M6():O7(this,b)),this.loaded?this.Gl:this.ri;case "quickCast":return 2===this.ym.length&&"cast-selector-receiver"===this.ym[1].key?(b&&M6(),!0):!1}};
g.k.uC=function(){this.Ob.uC()};
g.k.Qh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.oM.remote=M7;})(_yt_player);
